
version: 2

sources:
  - name: gz_data
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship

models:
  - name: raw_gz_product
    description: Nuestro modelo de producto
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
  - name: raw_gz_sales
    description: Nuestro modelo de ventas
    columns:
      - name: date_date
        description: La columna de fechas
      - name: orders_id
        description: Columna con llave foranea de orders
        tests:
          - unique
          - not_null
  - name: raw_gz_ship
    description: El modelo de envios
    columns:
      - name: orders_id
        description: Llave foranea de orders
        tests:
          - not_null
      - name: shipping_fee
        description: Impuesto de envio
        tests:
          - not_null
      - name: logcost
        description: Info de cost
        tests:
          - not_null
      - name: ship_cost
        description: Costos de envio
        tests:
          - not_null