
version: 2

sources:
  - name: gz_data
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - not_null
      - name: sales
        identifier: raw_gz_sales
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
      - name: ship
        identifier: raw_gz_ship

models:
  - name: stg_gz_raw_data__raw_gz_product
    description: Nuestro modelo de producto
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_gz_raw_data__raw_gz_sales
    description: Nuestro modelo de ventas
    columns:
      - name: date_date
        description: La columna de fechas
      - name: orders_id
        description: Columna con llave foranea de orders
        tests:
          - not_null

  - name: stg_gz_raw_data__raw_gz_ship
    description: El modelo de envios
    columns:
      - name: orders_id
        description: Llave foranea de orders
        tests:
          - not_null
      - name: shipping_fee
        description: Impuesto de envio
        tests:
          - not_null
      - name: logcost
        description: Info de cost
        tests:
          - not_null
      - name: ship_cost
        description: Costos de envio
        tests:
          - not_null